# Generated by Django 3.1.5 on 2021-03-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_auto_20210314_0024"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="property",
            name="longitude",
        ),
    ]
