# Generated by Django 3.2 on 2021-05-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20210403_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
