# Generated by Django 3.1.5 on 2021-02-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210224_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tenent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.tenant'),
        ),
    ]
