# Generated by Django 3.1.5 on 2021-03-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_tenent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='postcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
